name = "john-corp-website"
compatibility_date = "2025-04-29"
main = "./dist/worker.js"

[build]
command = "npm install && npm run build"
output_dir = "dist"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = "./dist"
