name = "john-corp-website"
compatibility_date = "2025-04-29"
main = "./dist/worker.js"

[build]
command = "npm install --no-package-lock && npm run build"
dist = "dist"
pages_build_output_dir = "dist"

[site]
bucket = "./dist"
